# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('ID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('sell_currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buy_currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rate', models.FloatField(default='')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
