# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eur2usd', models.FloatField(default='')),
                ('eur2gbp', models.FloatField(default='')),
                ('gbp2eur', models.FloatField(default='')),
                ('gbp2usd', models.FloatField(default='')),
                ('usd2eur', models.FloatField(default='')),
                ('usd2gbp', models.FloatField(default='')),
            ],
        ),
    ]
